export const SET_INPUT_VALUE = 'SET_INPUT_VALUE'

export const GET_EVENTS = 'GET_EVENTS'
export const GET_EVENTS_START = 'GET_EVENTS_START'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL'
