export const SET_INPUT_VALUE = 'SET_INPUT_VALUE'

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_FAIL = 'LOAD_CATEGORIES_FAIL'

export const GET_EVENTS_START = 'GET_EVENTS_START'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL'

export const GET_EVENT_DETAILS_START = 'GET_EVENT_DETAILS_START'
export const GET_EVENT_DETAILS_SUCCESS = 'GET_EVENT_DETAILS_SUCCESS'
export const GET_EVENT_DETAILS_FAIL = 'GET_EVENT_DETAILS_FAIL'

export const TOGGLE_MENU = 'TOGGLE_MENU'